site_name: Dwarf Fortress localization project

theme:
  name: material
  language: en

plugins:
  - i18n:
      default_language: en
      docs_structure: folder
      languages:
        en:
          name: English
        ru:
          name: Русский
