name: Deploy docs
on:
  push:
    branches:
      - master 
      - main
    paths:
      - '.github/workflows/deploy-docs.yml'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'docs/*'
      - 'mkdocs.yml'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: "poetry"
          cache-dependency-path: poetry.lock

      - name: Install dependencies
        run: poetry install --no-root

      - name: Deploy docs
        run: poetry run mkdocs gh-deploy --force
